name: delete
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 */8 * * *

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    name: delete-workflow-runs
    steps:
      - name: 删除在github空间的老固件
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.ACTIONS }}
          repository: ${{ github.repository }}
          retain_days: 0.5
          keep_minimum_runs: 0

      - name: 删除自动发布的老固件
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1         # 保留多少个发布不删除
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
